apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:masters
      rolearn: arn:aws:iam::665522198142:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
