$ vi aws-auth.yaml



apiVersion: v1

kind: ConfigMap

metadata:

  name: aws-auth

  namespace: kube-system
data:
  mapRoles: |
   - rolearn: arn:aws:iam::665522198142:role/eksctl-simple-jwt-api-nodegroup-NodeInstanceRole-LCYO9D4751B9
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:masters
        - system:nodes
   - rolearn: arn:aws:iam::665522198142:role/UdacityFlaskDeployCBKubectlRole
     username: build
     groups:
       - system:masters


$ kubectl apply -f aws-auth.yaml